version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
      - POSTGRES_USER=dev
      - PGDATA=/var/lib/postgresql/data/PGDATA
    volumes:
      - ./db:/var/lib/postgresql/data
