services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /home/chris/ssd/option_data:/app/db
    networks:
      webhost:
        ipv4_address: 172.10.1.220
    restart: unless-stopped
networks:
  webhost:
    name: webhost
    external: true
